### PR TITLE
WIP: Use exact alarm scheduling for API versions >= 19

### LINKED ISSUE #52: Alarm time is inexact for API versions => 19
> Note: Beginning with API 19 (KITKAT) alarm delivery is inexact: the OS will shift alarms in order to minimize wakeups and battery use. There are new APIs to support applications which need strict delivery guarantees; see setWindow(int, long, long, PendingIntent) and setExact(int, long, PendingIntent). Applications whose targetSdkVersion is earlier than API 19 will continue to see the previous behavior in which all alarms are delivered exactly when requested. 

([Source](https://developer.android.com/reference/android/app/AlarmManager.html))

For my device (running CM13, Android 6.0.1) the alarm times are very unreliable - sometimes more than an hour off. Since this application is supposed to help with medication intake times, I think reliable alarm times should be a critical priority in regards to battery usage - at least as important as your daily wake-up alarm. There are certain medications where even half an hour makes a large difference for the affected patients condition.

Since ```setExact``` only exists on API versions >= 19, conditional branching based on ```Build.VERSION.SDK_INT``` could be needed if support for older API versions must not be dropped.

### PR DESCRIPTION
**Pull request by fabian-z**
Fixes #52 

Tested for two days on my device (CM13, Android 6.0.1), alarm times are exact with these changes. No errors were observed, but I could not yet test on older devices. Also, no significant battery usage increase happened.
Looking forward to your testing and feedback.

### CODE REVIEW

**Comment by fabian-z** [comment]
This is still WIP, some issues with alarms not silencing after seeing the notification or opening the app occured for me after several days.

**Comment by angelpinheiro** [comment]
Hey Fabian, I'm back from holidays! I have been working for some time on a new version of the app that allows the management of several patients ([multi-patient branch](https://github.com/citiususc/calendula/tree/multi-patient)).  I you take a look at [AlarmScheduler](https://github.com/citiususc/calendula/blob/multi-patient/Calendula/src/main/java/es/usc/citius/servando/calendula/scheduling/AlarmScheduler.java) you will notice there are a lot of changes. Those changes will be on the master branch in the next days (and also on the app on Google Play), so I will wait to merge, because the changes on your PR will need some refactor. Even so, this issue is still relevant.

Anyway, next day alarms are all scheduled every day at 00:00 (look [here](https://github.com/citiususc/calendula/blob/master/Calendula/src/main/java/es/usc/citius/servando/calendula/CalendulaApp.java#L109) and [here](https://github.com/citiususc/calendula/blob/master/Calendula/src/main/java/es/usc/citius/servando/calendula/scheduling/AlarmReceiver.java#L50)), so there is no need to implement any kind of rescheduling. I think that "setRepeating" was there from previous versions without consequences.

**Comment by fabian-z** [comment]
Hi Ángel, thanks for your feedback! Hope you had nice holidays :smile: 
I must have missed the relevant scheduling code you pointed out on my dive into the codebase - this should be the misconception causing the issue I mentioned above.

I'll take a look at your new branch to try applying the fixes for the new Android versions when I find time, most likely sometime during the next week. Maybe a new PR will be the most sensible choice, depending on the amount of refactoring. 

If ```setRepeating``` is indeed unneeded, it should be easy to replace with the SDK version check calling the proper set method as in https://github.com/citiususc/calendula/pull/53/commits/5f8aa94768a4595e1cdd1fd91f5f26d1c91e37bc

**Comment by angelpinheiro** [comment]
Yes, I think that would be enough. Thanks you very much!

**Comment by angelpinheiro** [comment]
I'm closing this as it is fixed on cd3028d066ba140e78908074cc485675c917e5e3. 
Thank you very much anyway!

**Comment by fabian-z** [comment]
Sorry for the delay, I was too busy lately. Thank you for implementing the fix! I will test the develop branch on my device asap.

**Pull request closed without merging**
